# Generated by Django 6.0.1 on 2026-01-13 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='academic_year',
        ),
    ]
