# Generated by Django 6.0.1 on 2026-01-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='instituteinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='institute_logos/'),
        ),
    ]
