# Generated by Django 6.0.1 on 2026-01-11 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admission', 'Admission Fee'), ('january', 'January Fee'), ('february', 'February Fee'), ('mid_exam', 'Mid Exam'), ('final_exam', 'Final Exam'), ('test_exam', 'Test Exam')], max_length=50)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('exam_type', models.CharField(blank=True, choices=[('mid', 'Mid Exam'), ('final', 'Final Exam'), ('test', 'Test Exam')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FeesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.academicconfig')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.class')),
                ('fee_components', models.ManyToManyField(to='fees.feecomponent')),
            ],
        ),
        migrations.AddField(
            model_name='feecomponent',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feestype'),
        ),
        migrations.CreateModel(
            name='StudentFeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('fee_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feeplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admission')),
            ],
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('student_fee_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.studentfeerecord')),
            ],
        ),
    ]
