# Generated by Django 6.0.1 on 2026-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeplan',
            name='name',
            field=models.CharField(default='Standard Fee Plan', max_length=100),
        ),
    ]
