# Generated by Django 6.0.1 on 2026-01-16 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_payment_transection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='accept_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
