# Generated by Django 6.0.1 on 2026-01-11 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('fees', '0002_feeplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MakeFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feesfor')),
                ('february_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='february_fee', to='fees.feesfor')),
                ('january_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='january_fee', to='fees.feesfor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.admission')),
            ],
        ),
    ]
