# Generated by Django 6.0.1 on 2026-01-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_feesfor_makefees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feecomponent',
            name='fee_type',
        ),
        migrations.RemoveField(
            model_name='feeplan',
            name='fee_components',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='student_fee_record',
        ),
        migrations.RemoveField(
            model_name='feeplan',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='feeplan',
            name='class_assigned',
        ),
        migrations.RemoveField(
            model_name='studentfeerecord',
            name='fee_plan',
        ),
        migrations.RemoveField(
            model_name='makefees',
            name='february_fee',
        ),
        migrations.RemoveField(
            model_name='makefees',
            name='january_fee',
        ),
        migrations.RemoveField(
            model_name='makefees',
            name='admission_fee',
        ),
        migrations.RemoveField(
            model_name='makefees',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentfeerecord',
            name='student',
        ),
        migrations.DeleteModel(
            name='FeesType',
        ),
        migrations.DeleteModel(
            name='FeeComponent',
        ),
        migrations.DeleteModel(
            name='FeePayment',
        ),
        migrations.DeleteModel(
            name='FeePlan',
        ),
        migrations.DeleteModel(
            name='FeesFor',
        ),
        migrations.DeleteModel(
            name='MakeFees',
        ),
        migrations.DeleteModel(
            name='StudentFeeRecord',
        ),
    ]
