# Generated by Django 6.0.1 on 2026-01-12 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feecategory',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
